# Generated by Django 4.2.6 on 2023-10-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zotero_id", models.CharField(max_length=100, unique=True)),
                ("content", models.JSONField(default=dict)),
                ("comment", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zotero_id", models.CharField(max_length=100, unique=True)),
                ("content", models.JSONField(default=dict)),
                ("attachment_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("library_id", models.CharField(max_length=100, unique=True)),
                ("library_version", models.IntegerField()),
            ],
        ),
    ]
