# Generated by Django 4.2.7 on 2023-11-22 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
        ('lidia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='zotero_id',
        ),
        migrations.AddField(
            model_name='publication',
            name='zotero_publication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sync.publication', to_field='zotero_id', verbose_name='Zotero publication'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='relation_type',
            field=models.CharField(choices=[('', 'none'), ('contradicts', 'contradicts'), ('generalizes', 'generalizes'), ('invalidates', 'invalidates'), ('specialcase', 'is a special case of'), ('supports', 'supports')], default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='articleterm',
            name='term',
            field=models.CharField(max_length=100, unique=True, verbose_name='article term'),
        ),
        migrations.AlterField(
            model_name='baseannotation',
            name='textselection',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='continuationannotation',
            name='start_annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuation_annotations', to='lidia.annotation'),
        ),
        migrations.AlterField(
            model_name='lidiaterm',
            name='term',
            field=models.CharField(max_length=100, verbose_name='LIDIA term'),
        ),
        migrations.AlterField(
            model_name='lidiaterm',
            name='vocab',
            field=models.CharField(choices=[('lol', 'Lexicon of Linguistics'), ('custom', 'custom')], max_length=6, verbose_name='vocabulary'),
        ),
        migrations.AlterField(
            model_name='termgroup',
            name='annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termgroups', to='lidia.annotation'),
        ),
        migrations.AlterField(
            model_name='termgroup',
            name='articleterm',
            field=models.ForeignKey(help_text='Term that was used in the resource', null=True, on_delete=django.db.models.deletion.CASCADE, to='lidia.articleterm', verbose_name='article term'),
        ),
        migrations.AlterField(
            model_name='termgroup',
            name='lidiaterm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lidia.lidiaterm', verbose_name='LIDIA term'),
        ),
        migrations.AlterField(
            model_name='termgroup',
            name='termtype',
            field=models.CharField(choices=[('definiendum', 'Definiendum'), ('definiens', 'Definiens'), ('other', 'Other')], max_length=11, null=True, verbose_name='term type'),
        ),
    ]
