# Generated by Django 4.2.7 on 2024-03-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidia', '0002_alter_category_options_remove_publication_zotero_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lidiaterm',
            name='vocab',
            field=models.CharField(choices=[('lidia', 'LIDIA'), ('custom', 'custom')], max_length=6, verbose_name='vocabulary'),
        ),
    ]
