# Generated by Django 4.2.7 on 2023-11-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lidia", "0002_alter_annotation_argcont_alter_annotation_arglang_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="lidia_id",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="LIDIA ID"
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="zotero_id",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Zotero ID"
            ),
        ),
    ]
