# Generated by Django 4.2.7 on 2024-03-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidia', '0003_alter_lidiaterm_vocab'),
    ]

    operations = [
        migrations.AddField(
            model_name='lidiaterm',
            name='urls',
            field=models.JSONField(blank=True, null=True, verbose_name='URLs'),
        ),
    ]
