# Generated by Django 4.2.7 on 2023-11-07 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lidia", "0003_annotation_lidia_id_alter_annotation_zotero_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="relation_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lidia.annotation",
                to_field="lidia_id",
            ),
        ),
    ]
