name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'main'
      - 'release/**'
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install setuptools  # requirement for iso639-lang on Python>=3.12
      - name: Lint with ruff
        run: |
          pip install ruff
          ruff --output-format=github --target-version=py38 .
      - name: Test with pytest
        run: |
          cp lidiabrowser/lidiabrowser/.env.dist lidiabrowser/lidiabrowser/.env
          pytest lidiabrowser
